version: '3.7'

services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: file-uploader-httpbin
    ports:
      - "127.0.0.1:16234:80"
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 64M
        limits:
          cpus: '0.2'
          memory: 64M
    security_opt:
      - "no-new-privileges:true"
    networks:
      - file-uploader-network

networks:
  file-uploader-network:
    driver: bridge
